<?php

namespace Database\Seeders;

use App\Models\JobPosition;
use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;

class JobPositionSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $jobPositions = [
            "ACCOUNT PAYABLE RISM & MKLI", "ADMIN COD", "ADMIN DATA SUPPORT TECNO", "ADMIN DATA SUPPORT ZTE",
            "ADMIN GROSIR LEADER", "ADMIN PEMBELIAN", "ADMIN PROGRAM", "ADMIN RETUR", "ADMIN SOCMED", "APPRAISAL",
            "AR COORDINATOR", "AREA MANAGER", "AREA SALES COORDINATOR REALME", "AREA SALES MANAGER REALME",
            "Asst. Sales Manager", "AUDIT COORDINATOR", "AUDIT FIELD TEAM LEADER", "AUDIT STOCK OPNAME & VISIBILITY",
            "BOARD OF DIRECTOR", "BUSINESS DEVELOPMENT COORDINATOR", "BUSINESS DEVELOPMENT LEADER", "CASHIER OFFICER (WJ4)",
            "CHIEF INTERNAL AUDIT", "CHIEF OPERATIONAL OFFICER", "CHIEF SALES OFFICER", "CONTENT CREATOR", "COOK",
            "COORDINATOR FINANCE", "COORDINATOR WAREHOUSE DAN LOGISTIK", "Crew Store", "CS MARKETPLACE", "CSO & COO",
            "CUSTOMER SERVICE", "CUSTOMER SERVICE MARKET PLACE", "Data Analyst", "DATA ANALYST COORDINATOR",
            "DESIGN CREATOR", "DESIGN GRAFIS", "DESIGN GRAFIS MKLI", "DIGITAL MARKETING LEADER", "DRIVER", "DRIVER LOGISTIK",
            "DRIVER MKLI", "FIELD INTERNAL AUDIT MKLI", "FINANCE & ACCOUNTING MANAGER", "FINANCE ACCOUNTING TAX MANAGER",
            "FINANCE AUDIT COORDINATOR", "GADGET SPECIALIST (CJ1)", "GADGET SPECIALIST (WJ1)", "GADGET SPECIALIST (WJ2)",
            "GADGET SPECIALIST (WJ3)", "GADGET SPECIALIST (WJ4)", "GADGET SPECIALIST LEADER (CJ1)",
            "GADGET SPECIALIST LEADER (WJ1)", "GADGET SPECIALIST LEADER (WJ2)", "GADGET SPECIALIST LEADER (WJ3)",
            "GENERAL AFFAIR COORDINATOR", "GENERAL AFFAIR ENGINEER", "GENERAL AFFAIR MKLI", "GENERAL AFFAIR OFFICER",
            "GENERAL MANAGER ZTE", "GOLDSMITH", "HANDPHONE ENGINEER", "HEAD STORE (CJ1)", "HEAD STORE (WJ1)",
            "HEAD STORE (WJ2)", "HEAD STORE AMAZY", "HR SUPERVISOR", "HUMAN CAPITAL MANAGER RISM & MKLI",
            "IT Support Afiliasi", "IT SUPPORT COORDINATOR", "IT Support Helpdesk & Networking", "IT Support Mobile & CCTV",
            "KASIR", "KEPALA GUDANG", "KEPALA GUDANG AKSESORIS", "KEPALA TEKNISI", "KURIR", "LEADER IT SUPPORT",
            "LEADER REFUND & PROGRAM", "LEADER RETUR", "LEADER SHOWROOM", "LEADER WAREHOUSE DAN LOGISTIK", "LEGAL COORDINATOR",
            "Management Trainee Production", "MANAGER OPERASIONAL", "MANAGER RETAIL AUTO EV", "MT - AREA SALES MANAGER ZTE",
            "MT - STAFF FINANCE KAS", "MT ADMIN E-COMMERCE", "MT ADMIN PROSES ONLINE", "MT AR", "MT FINANCE STAFF E-COMMERCE",
            "MT HEAD STORE", "MT KURIR", "MT SALES TECNO", "MT SALES ZTE", "MT STAFF INTERNAL AUDIT",
            "MT SUPERVISOR SALES TECNO", "MT SUPPLY CHAIN & TRANSLATOR", "MT SUPPLY CHAIN OFFICER", "MT TAX SUPERVISOR",
            "MT WAREHOUSE LEADER ONLINE", "MT WAREHOUSE STAFF", "OFFICE BOY", "ORGANIZATION DEVELOPMENT",
            "PERSONALIA MKLI & RISM", "PERSONNEL COORDINATOR", "PERSONNEL OFFICER", "PJS MANAGER HUMAN CAPITAL AFILIASI",
            "PURCHASE & LOGISTIC COORDINATOR", "RELATIONSHIP OFFICER", "RETAIL STORE COORDINATOR (CJ1)",
            "RETAIL STORE COORDINATOR (WJ1)", "RETAIL STORE COORDINATOR (WJ2)", "RETAIL STORE COORDINATOR (WJ3)",
            "RETAIL STORE MANAGER", "SALES AREA ITEL REALME", "SALES ASSOCIATE", "SALES ORAIMO WJ", "SECRETARY OF CEO",
            "SECURITY", "SENIOR ACCOUNTING STAFF MKLI", "SPV FINANCE ACCOUNTING", "STAFF ACCOUNTING", "STAFF ACCOUNTING RESTO",
            "STAFF ADMIN LOGISTIK", "STAFF AR", "STAFF AR RISM", "STAFF CHECKER", "STAFF FINANCE EDC", "STAFF FINANCE TRANSFER",
            "STAFF FINANCE TRANSFER MKLI RISM", "STAFF INTERNAL AUDIT", "STAFF INTERNAL AUDIT MKLI", "STAFF KAS BESAR",
            "STAFF KPI", "STAFF PAJAK", "STAFF PAJAK MKLI RISM", "STAFF PURCHASING (1)", "STAFF PURCHASING (2)",
            "STAFF PURCHASING ONLINE", "STAFF RETAIL STORE", "STAFF RETUR", "STAFF WAREHOUSE", "SUPERVISOR E-COMMERCE",
            "SUPPLY CHAIN MANAGER", "TALENT ACQUISITION OFFICER", "TALENT ACQUISITION OFFICER MKLI", "TEAM LEADER ACCOUNTING",
            "TEAM LEADER OFFLINE", "TEAM LEADER PEMBELIAN", "TELEMARKETING BIG 1", "TELEMARKETING BIG 2",
            "TELEMARKETING BIG 3", "TUKANG KEMASAN", "WEB DEVELOPMENT"
        ];

        foreach ($jobPositions as $position) {
            JobPosition::create(['name' => $position]);
        }
    }
}
